First attempt at automating Github releases

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,106 +1,153 @@
 # Build script for continuous integration builds with Azure Pipelines
 
-strategy:
-  matrix:
-    gcc:
-      imageName: 'ubuntu-18.04'
-      compiler: g++-9
-      flags: '-DCMAKE_BUILD_TYPE=Release'
-    clang:
-      imageName: 'ubuntu-18.04'
-      compiler: clang++-9
-      flags: '-DCMAKE_BUILD_TYPE=Debug -DSLANG_COVERAGE=ON -DSLANG_SANITIZERS=undefined,address "-DCMAKE_CXX_CLANG_TIDY=/usr/lib/llvm-9/bin/clang-tidy;-quiet;-checks=-*,clang-analyzer-*,bugprone-*,performance-*,modernize-*,-modernize-use-auto,-modernize-use-trailing-return-type,-modernize-raw-string-literal,-modernize-use-nodiscard,-bugprone-suspicious-semicolon,-bugprone-branch-clone,-bugprone-sizeof-expression,-clang-analyzer-cplusplus.NewDelete*,-clang-analyzer-cplusplus.InnerPointer,misc-*,-misc-non-private-member-variables-in-classes,-modernize-avoid-c-arrays"'
-    msvc:
-      imageName: 'windows-2019'
+jobs:
+- job: Build
+  strategy:
+    matrix:
+      gcc:
+        imageName: 'ubuntu-18.04'
+        compiler: g++-9
+        flags: '-DCMAKE_BUILD_TYPE=Release'
+        isLinux: true
+        isGCC: true
+      clang:
+        imageName: 'ubuntu-18.04'
+        compiler: clang++-9
+        flags: '-DCMAKE_BUILD_TYPE=Debug -DSLANG_COVERAGE=ON -DSLANG_SANITIZERS=undefined,address "-DCMAKE_CXX_CLANG_TIDY=/usr/lib/llvm-9/bin/clang-tidy;-quiet;-checks=-*,clang-analyzer-*,bugprone-*,performance-*,modernize-*,-modernize-use-auto,-modernize-use-trailing-return-type,-modernize-raw-string-literal,-modernize-use-nodiscard,-bugprone-suspicious-semicolon,-bugprone-branch-clone,-bugprone-sizeof-expression,-clang-analyzer-cplusplus.NewDelete*,-clang-analyzer-cplusplus.InnerPointer,misc-*,-misc-non-private-member-variables-in-classes,-modernize-avoid-c-arrays"'
+        isLinux: true
+        isClang: true
+      msvc:
+        imageName: 'windows-2019'
+        isWindows: true
 
-pool:
-  vmImage: $(imageName)
+  pool:
+    vmImage: $(imageName)
 
-steps:
-- task: UsePythonVersion@0
+  steps:
+  - task: UsePythonVersion@0
 
-- script: |
-    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-    sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" -y
-    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
-    sudo apt-get update
-    sudo apt-get install -y gcc-9 g++-9 clang-9 clang-tidy-9
-  displayName: 'Install GCC and Clang'
-  condition: eq(variables['Agent.OS'], 'Linux')
+  - script: |
+      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
+      sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" -y
+      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
+      sudo apt-get update
+      sudo apt-get install -y gcc-9 g++-9 clang-9 clang-tidy-9
+    displayName: 'Install GCC and Clang'
+    condition: variables.isLinux
 
-- script: |
-    export PATH="$HOME/.local/bin:$PATH"
-    sudo apt-get install -y python3-setuptools python3-pip
-    pip3 install wheel
-    pip3 install conan
-    conan user
-    conan --version
-  displayName: 'Install Conan (Linux)'
-  condition: eq(variables['Agent.OS'], 'Linux')
+  - script: |
+      export PATH="$HOME/.local/bin:$PATH"
+      sudo apt-get install -y python3-setuptools python3-pip
+      pip3 install wheel
+      pip3 install conan
+      conan user
+      conan --version
+    displayName: 'Install Conan (Linux)'
+    condition: variables.isLinux
 
-- script: |
-    pip3 install conan
-    conan user
-    conan --version
-  displayName: 'Install Conan (MacOS)'
-  condition: eq(variables['Agent.OS'], 'Darwin')
+  - script: |
+      pip3 install conan
+      conan user
+      conan --version
+    displayName: 'Install Conan (MacOS)'
+    condition: variables.isMac
 
-- script: |
-    pip install conan
-    conan user
-    conan --version
-  displayName: 'Install Conan (Windows)'
-  condition: eq(variables['Agent.OS'], 'Windows_NT')
+  - script: |
+      pip install conan
+      conan user
+      conan --version
+    displayName: 'Install Conan (Windows)'
+    condition: variables.isWindows
 
-- script: |
-    mkdir build
-    cd build
-    cmake -DCMAKE_CXX_COMPILER=$(compiler) -DCI_BUILD=ON $(flags) ..
-    make -j 8
-  displayName: 'Build (Linux)'
-  condition: eq(variables['Agent.OS'], 'Linux')
+  - script: |
+      mkdir build
+      cd build
+      cmake -DCMAKE_CXX_COMPILER=$(compiler) -DCI_BUILD=ON $(flags) ..
+      make -j 8
+    displayName: 'Build (Linux)'
+    condition: variables.isLinux
 
-- script: |
-    mkdir build
-    cd build
-    cmake -G "Visual Studio 16 2019" ..
-  displayName: 'Generate VS Solution'
-  condition: eq(variables['Agent.OS'], 'Windows_NT')
+  - script: |
+      mkdir build
+      cd build
+      cmake -G "Visual Studio 16 2019" ..
+    displayName: 'Generate VS Solution'
+    condition: variables.isWindows
 
-- task: VSBuild@1
-  inputs:
-    solution: build/slang.sln
-    platform: x64
-    configuration: Release
-    maximumCpuCount: true
-  displayName: 'Build (Windows)'
-  condition: eq(variables['Agent.OS'], 'Windows_NT')
+  - task: VSBuild@1
+    inputs:
+      solution: build/slang.sln
+      platform: x64
+      configuration: Release
+      maximumCpuCount: true
+    displayName: 'Build (Windows)'
+    condition: variables.isWindows
 
-- script: |
-    mkdir build
-    cd build
-    cmake -G "Xcode" ..
-    cmake --build .
-  displayName: 'Build (MacOS)'
-  condition: eq(variables['Agent.OS'], 'Darwin')
+  - script: |
+      mkdir build
+      cd build
+      cmake -G "Xcode" ..
+      cmake --build .
+    displayName: 'Build (MacOS)'
+    condition: variables.isMac
 
-- script: |
-    export LLVM_PROFILE_FILE=%p.profraw
-    cd build
-    ctest --output-on-failure
-  displayName: 'Run tests (Linux)'
-  condition: or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))
+  - script: |
+      export LLVM_PROFILE_FILE=%p.profraw
+      cd build
+      ctest --output-on-failure
+    displayName: 'Run tests (Linux)'
+    condition: or(variables.isLinux, variables.isMac)
 
-- script: |
-    cd build
-    ctest -C Release --output-on-failure
-  displayName: 'Run tests (Windows)'
-  condition: eq(variables['Agent.OS'], 'Windows_NT')
+  - script: |
+      cd build
+      ctest -C Release --output-on-failure
+    displayName: 'Run tests (Windows)'
+    condition: variables.isWindows
 
-- script: |
-    cd build
-    find . -name *.profraw -exec llvm-profdata-9 merge -o merged.profdata -sparse {} + ;
-    llvm-cov-9 show bin/unittests -instr-profile=merged.profdata > coverage.txt
-    bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN) || echo 'Codecov failed to upload'
-  displayName: 'Upload code coverage'
-  condition: eq(variables['compiler'], 'clang++-9')
+  - script: |
+      cd build
+      find . -name *.profraw -exec llvm-profdata-9 merge -o merged.profdata -sparse {} + ;
+      llvm-cov-9 show bin/unittests -instr-profile=merged.profdata > coverage.txt
+      bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN) || echo 'Codecov failed to upload'
+    displayName: 'Upload code coverage'
+    condition: variables.isClang
+
+  - task: PublishPipelineArtifact@0
+    inputs:
+      artifactName: 'SLANG_ZIP_LINUX'
+      targetPath: 'products_lin/'
+    displayName: Publish Linux Zip
+    condition: variables.isGCC
+
+  - task: PublishPipelineArtifact@0
+    inputs:
+      artifactName: 'SLANG_ZIP_WIN'
+      targetPath: 'products_win/'
+    displayName: Publish Windows Zip
+    condition: variables.isWindows
+
+- job: UpdateGithubRelease
+  dependsOn: Build
+  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/azure-test')))
+
+  steps:
+  - task: DownloadPipelineArtifact@0
+    inputs:
+      artifactName: 'SLANG_ZIP_LINUX'
+      targetPath: $(Build.ArtifactStagingDirectory)
+
+  - task: DownloadPipelineArtifact@0
+    inputs:
+      artifactName: 'SLANG_ZIP_WIN'
+      targetPath: $(Build.ArtifactStagingDirectory)
+
+  - task: GitHubRelease@0
+    displayName: "Update Github Release"
+    inputs:
+      gitHubConnection: github.com_MikePopoloski
+      repositoryName: MikePopoloski/slang
+      action: edit
+      tag: nightly
+      target: '$(Build.SourceVersion)'
+      assets: $(Build.ArtifactStagingDirectory)/*.zip
+      isPreRelease: true
